name: publish
on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: production
      url: https://npmjs.com/package/my-deprecations
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
      - run: npm ci --no-audit
      - run: npm test
      - run: npm publish
